### ISSUE TITLE
Crash `IndexError: string not matched`

### ISSUE THREAD

**Issue by felginep** [faberNovel/ad_localize#67]
When using the following keys: 
```
aaaa.bbbb      | small | small |
aaaa.bbbb.cccc | big | big |
```

The following command `bundle exec ad_localize -k SHEET_ID -o json -t src/assets/localizables` gives the following error:

```
bundler: failed to load command: ad_localize (/Users/felginep/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/bin/ad_localize)
IndexError: string not matched
  /Users/felginep/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/ad_localize-4.0.8/lib/ad_localize/mappers/locale_wording_to_hash.rb:13:in `[]='
  /Users/felginep/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/ad_localize-4.0.8/lib/ad_localize/mappers/locale_wording_to_hash.rb:13:in `block (2 levels) in map'
  /Users/felginep/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/ad_localize-4.0.8/lib/ad_localize/mappers/locale_wording_to_hash.rb:7:in `each'
  /Users/felginep/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/ad_localize-4.0.8/lib/ad_localize/mappers/locale_wording_to_hash.rb:7:in `each_with_index'
  /Users/felginep/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/ad_localize-4.0.8/lib/ad_localize/mappers/locale_wording_to_hash.rb:7:in `block in map'
  /Users/felginep/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/ad_localize-4.0.8/lib/ad_localize/mappers/locale_wording_to_hash.rb:5:in `each'
  /Users/felginep/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/ad_localize-4.0.8/lib/ad_localize/mappers/locale_wording_to_hash.rb:5:in `each_with_object'
  /Users/felginep/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/ad_localize-4.0.8/lib/ad_localize/mappers/locale_wording_to_hash.rb:5:in `map'
  /Users/felginep/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/ad_localize-4.0.8/lib/ad_localize/serializers/json_serializer.rb:9:in `render'
  /Users/felginep/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/ad_localize-4.0.8/lib/ad_localize/interactors/platforms/export_json_locale_wording.rb:13:in `call'
  /Users/felginep/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/ad_localize-4.0.8/lib/ad_localize/interactors/export_wording.rb:15:in `block (2 levels) in call'
  /Users/felginep/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/ad_localize-4.0.8/lib/ad_localize/interactors/export_wording.rb:12:in `each'
  /Users/felginep/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/ad_localize-4.0.8/lib/ad_localize/interactors/export_wording.rb:12:in `block in call'
  /Users/felginep/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/ad_localize-4.0.8/lib/ad_localize/interactors/export_wording.rb:11:in `each'
  /Users/felginep/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/ad_localize-4.0.8/lib/ad_localize/interactors/export_wording.rb:11:in `call'
  /Users/felginep/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/ad_localize-4.0.8/lib/ad_localize/interactors/export_csv_files.rb:13:in `call'
  /Users/felginep/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/ad_localize-4.0.8/lib/ad_localize/interactors/export_g_spreadsheet.rb:35:in `export_without_service_account'
  /Users/felginep/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/ad_localize-4.0.8/lib/ad_localize/interactors/export_g_spreadsheet.rb:14:in `call'
  /Users/felginep/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/ad_localize-4.0.8/lib/ad_localize/interactors/execute_export_request.rb:17:in `call'
  /Users/felginep/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/ad_localize-4.0.8/lib/ad_localize/cli.rb:7:in `start'
  /Users/felginep/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/ad_localize-4.0.8/exe/ad_localize:3:in `<top (required)>'
  /Users/felginep/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/bin/ad_localize:23:in `load'
  /Users/felginep/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/bin/ad_localize:23:in `<top (required)>'
```

**Comment by felginep** [comment]
Thinking about it, it's not really a bug because we can't get a correct json out of the wording. But maybe we could have a nice warning instead of a crash, and / or a word in the documentation about this.

**Comment by felginep** [comment]
Dup #59
